question_data = [

        {"category": "Entertainment: Television",
         "type": "boolean",
         "difficulty": "medium",
         "question": "AMC&#039;s &quot;The Walking Dead&quot;, Rick, Carl, Daryl, Morgan, Carol and Maggie were introduced to us in Season 1.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
         "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in fights&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In &quot;Super Mario 64&quot;, collecting 100 coins on a level will give you a 1-UP.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                           "question": "Toronto is the capital city of the North American country of Canada.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "Stephen Chbosky wrote the book &#039;The Perks of Being A Wallflower&#039;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "Kublai Khan is the grandchild of Genghis Khan?", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
         "question": "In &quot;Star Trek: The Next Generation&quot;, Data is the only android in existence.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "During pre-production of &quot;Super Mario Bros.&quot;, Mario originally was meant to shoot bullets.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The Lord of The Rings&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]}]

